services:
  shielddns:
    build: .
    image: shielddns:test
    ports:
      - "853:853"
    environment:
      - UPSTREAM_DNS=1.1.1.1
      - CERT_FILE=/certs/server.crt
      - KEY_FILE=/certs/server.key
    volumes:
      - ./certs:/certs
